export const PRODUCT_HOME_REQUEST = 'PRODUCT_HOME_REQUEST'
export const PRODUCT_HOME_SUCCESS = 'PRODUCT_HOME_SUCCESS'
export const PRODUCT_HOME_FAIL = 'PRODUCT_HOME_FAIL'

// export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
// export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
// export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'